name: build

on:
  push:
    branches: [master]
  repository_dispatch:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
  
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GHUB_USERNAME: ${{ secrets.GHUB_USERNAME }}
      GHUB_ACCESS_TOKEN: ${{ secrets.GHUB_ACCESS_TOKEN }}
 
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        # avoid shallow clone to ensure correct sonarqube auto assignment
        fetch-depth: 0
            
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
          
    - name: Configure servers
      uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: '[{"id": "sapl", "username": "${env.GHUB_USERNAME}", "password": "${env.GHUB_ACCESS_TOKEN}"}]'
        
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v2      
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven (JUnit, JaCoCo, Sonar) 
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.host.url=https://sonar.ftk.de -Dsonar.login=${SONAR_TOKEN} -Dsonar.exclusions=**/xtext-gen/**/*,**/xtend-gen/**/*,**/emf-gen/**/*
             
    - name: Clean up local repository before caching
      if: ${{ always() }}
      run: rm -rf /.m2/repository/io/sapl
      
